# This file was auto generated by Valama 0.1.2. Do not modify it.
set(project_name "xmi_gen")
set(xmi_gen_VERSION "0.0.0")
set(required_pkgs
"gee-1.0"
"gio-2.0"
"glib-2.0"
"gobject-2.0"
"granite"
"gtk+-3.0"
)
set(srcfiles
"src/Attribute.vala"
"src/main.vala"
)
set(vapifiles
"vapi/config.vapi"
)
